services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: munin
      POSTGRES_PASSWORD: munin
      POSTGRES_DB: muninn_library_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: