default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: muninn_library_development
  username: muninn
  password: <%= ENV['MUNINN_LIBRARY_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: muninn_library_test
  username: muninn
  password: <%= ENV['MUNINN_LIBRARY_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: muninn_library_production
  username: muninn
  password: <%= ENV['MUNINN_LIBRARY_DATABASE_PASSWORD'] %>
