default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: muninn_library_development

test:
  <<: *default
  database: muninn_library_test

production:
  <<: *default
  database: muninn_library_production
  username: <%= ENV['MUNINN_LIBRARY_DATABASE_USER'] %>
  password: <%= ENV['MUNINN_LIBRARY_DATABASE_PASSWORD'] %>
